name: RecallBookDeploy

on:
  push:
    branches:
    - 'main'

jobs:
  deployrecallbook:
    name: DeployRecallbook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Lektor
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install lektor:
      - run: lektor build
      - run: lektor deploy ghpages-https
        if: env.DEPLOY == 'true'
        env:
        LEKTOR_DEPLOY_USERNAME: lektor
        LEKTOR_DEPLOY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      

      

