name: LektorBuildup
on:
  push:
    branches: ["master"]
jobs:
  build_lektor:
    runs-on: ubuntu-latest
    steps:
      - name: Installing python
      - run: |
        apt update
        apt install python3
        apt install python3-pip
        pip3 install lektor
      - name: Building
      - run: lektor build -O public
  deploy_lektor:
    uses: build_lektor
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public